language: node_js
node_js:
- stable
git:
  depth: 10
sudo: false
addons:
  sauce_connect: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm run $COMMAND
env:
  matrix:
  - COMMAND=test
  - COMMAND=report-coverage
  - COMMAND=test-browser
  global:
  - secure: sg7XninkGV8c95tZgZDu9dDL22TqrDKUdES+I92H+3A9vY9GZVtFpp9l5AKLLrdj7FjJ+fSsMT1XN+zE3Ljj2EpHVJqNAqo0CmNYm+lfeyI6Z50eOeuGCsjaJPiMNpeD32nghG7tIBl4JVG0hcHs+AkFtWGQoj7n+8sJXWNwE9E=
  - secure: iHZwuxZUEYRujfoDt2rZJXq0o/15j0FpJFEoV2pzhq+zUIuqbuS9vUzvE0dpfvYq+MkrIe77O2q8cRilNjw5zRZltmU6HXHKq6qRyS+vbhiXEMzm4ucvQLDHDejSq5Xrfv+yOg0z5JBzSesrP4h6l50ohvRZGtkmGXRFN/zA0Rs=
  - secure: U2CJxbwO5HV9X7T+WnduZr4ZbcOB8tE/05q+3fi/X0zaSxgOTG7lOmngiNjnFB1lJXRS00iCE8QJ2pplrltGlcAeJLx1/fCOc5jmBbVuf0jt/qT5cKN8i87PO6SSdr7dhjwFzrqOxJ6AzMOO69nw6R7+stQaAvQCXP/Gg0szfWA=
branches:
  only:
  - master
